config/routes.rb
Rapidfire::Engine.routes.draw do
  resources :surveys do
    get 'results', on: :member

    resources :questions
    resources :attempts, only: [:new, :create, :edit, :update, :show]
  end

  root :to => "surveys#index"
end

app/models/rapidfire/answer.rb
module Rapidfire
  class Answer < ActiveRecord::Base
    belongs_to :question
    belongs_to :attempt, inverse_of: :answers

    validates :question, :attempt, presence: true
    validate  :verify_answer_text

    private

    def verify_answer_text
      return false unless question.present?
      question.validate_answer(self)
    end
  end
end

app/models/rapidfire/attempt.rb
module Rapidfire
  class Attempt < ActiveRecord::Base
    belongs_to :survey
    has_many   :answers, inverse_of: :attempt, autosave: true

    if Rails::VERSION::MAJOR >= 5
      belongs_to :user, polymorphic: true, optional: true
    else
      belongs_to :user, polymorphic: true
    end
  end
end

app/models/rapidfire/question.rb
module Rapidfire
  class Question < ActiveRecord::Base
    belongs_to :survey, :inverse_of => :questions
    has_many   :answers

    default_scope { order(:position) }

    validates :survey, :question_text, :presence => true
    serialize :validation_rules

    def self.inherited(child)
      child.instance_eval do
        def model_name
          Question.model_name
        end
      end

      super
    end

    def rules
      validation_rules || {}
    end

    # answer will delegate its validation to question, and question
    # will inturn add validations on answer on the fly!
    def validate_answer(answer)
      if rules[:presence] == "1"
        answer.validates_presence_of :answer_text
      end

      if rules[:minimum].present? || rules[:maximum].present?
        min_max = { minimum: rules[:minimum].to_i }
        min_max[:maximum] = rules[:maximum].to_i if rules[:maximum].present?

        answer.validates_length_of :answer_text, min_max
      end
    end
  end
end

app/models/rapidfire/questions/checkbox.rb
module Rapidfire
  module Questions
    class Checkbox < Rapidfire::Question
      validates :answer_options, :presence => true
      attr_accessor :default_text
      def placeholder
        ""
      end
      def options
        answer_options.split(Rapidfire.answers_delimiter)
      end

      def validate_answer(answer)
        super(answer)

        if rules[:presence] == "1" || answer.answer_text.present?
          answer.answer_text.split(Rapidfire.answers_delimiter).each do |value|
            answer.errors.add(:answer_text, :invalid) unless options.include?(value)
          end
        end
      end
    end
  end
end

app/models/rapidfire/questions/date.rb
module Rapidfire
  module Questions
    class Date < Rapidfire::Question
      def validate_answer(answer)
        super(answer)

        if rules[:presence] == "1" || answer.answer_text.present?
          begin  ::Date.parse(answer.answer_text.to_s)
          rescue ArgumentError => e
            answer.errors.add(:answer_text, :invalid)
          end
        end
      end
    end
  end
end

app/models/rapidfire/questions/long.rb
module Rapidfire
  module Questions
    class Long < Rapidfire::Question
    end
  end
end

app/models/rapidfire/questions/numeric.rb
module Rapidfire
  module Questions
    class Numeric < Rapidfire::Question
      def validate_answer(answer)
        super(answer)

        if rules[:presence] == "1" || answer.answer_text.present?
          gt_or_lt = {}
          if rules[:greater_than_or_equal_to].present?
            gt_or_lt[:greater_than_or_equal_to] = rules[:greater_than_or_equal_to].to_i
          end
          if rules[:less_than_or_equal_to].present?
            gt_or_lt[:less_than_or_equal_to] = rules[:less_than_or_equal_to].to_i
          end

          answer.validates_numericality_of :answer_text, gt_or_lt
        end
      end
    end
  end
end

app/models/rapidfire/questions/radio.rb
module Rapidfire
  module Questions
    class Radio < Select
    end
  end
end

app/models/rapidfire/questions/select.rb
module Rapidfire
  module Questions
    class Select < Rapidfire::Question
      validates :answer_options, :presence => true

      def options
        answer_options.split(Rapidfire.answers_delimiter)
      end

      def validate_answer(answer)
        super(answer)

        if rules[:presence] == "1" || answer.answer_text.present?
          answer.validates_inclusion_of :answer_text, :in => options
        end
      end
    end
  end
end

app/models/rapidfire/questions/short.rb
module Rapidfire
  module Questions
    class Short < Rapidfire::Question
    end
  end
end

app/models/rapidfire/survey.rb
module Rapidfire
  class Survey < ActiveRecord::Base
    has_many  :attempts
    has_many  :questions
    has_many :attempts

    validates :name, :presence => true
  end
end

app/controllers/rapidfire/application_controller.rb
module Rapidfire
  class ApplicationController < ::ApplicationController
    if Rapidfire.layout
      layout Rapidfire.layout
    end

    helper_method :can_administer?

    def authenticate_administrator!
      unless can_administer?
        raise Rapidfire::AccessDenied.new("cannot administer questions")
      end
    end

    # Override prefixes to consider the scoped.
    # for method current_user
    def scoped
      :user
    end
  end
end

app/controllers/rapidfire/attempts_controller.rb
module Rapidfire
  class AttemptsController < Rapidfire::ApplicationController
    before_action :find_survey!

    def show
      @attempt = @survey.attempts.find_by(attempt_params_for_find)
    end

    def new
      @attempt_builder = AttemptBuilder.new(attempt_params)
    end

    def create
      @attempt_builder = AttemptBuilder.new(attempt_params)

      if @attempt_builder.save
        redirect_to after_answer_path_for
      else
        render :new
      end
    end

    def edit
      @attempt_builder = AttemptBuilder.new(attempt_params)
    end

    def update
      @attempt_builder = AttemptBuilder.new(attempt_params)

      if @attempt_builder.save
        redirect_to after_answer_path_for
      else
        render :edit
      end
    end

    private

    def find_survey!
      @survey = Survey.find(params[:survey_id])
    end

    def attempt_params
      answer_params = { params: (params[:attempt] || {}) }
      answer_params.merge(user: current_user, survey: @survey, attempt_id: params[:id])
    end

    def attempt_params_for_find
      these_params = attempt_params
      these_params[:id] = these_params.delete(:attempt_id)
      these_params
    end

    # Override path to redirect after answer the survey
    # Write:
    #   # my_app/app/decorators/controllers/rapidfire/attempts_controller_decorator.rb
    #   Rapidfire::AttemptsController.class_eval do
    #     def after_answer_path_for
    #       main_app.root_path
    #     end
    #   end
    def after_answer_path_for
      if @survey.after_survey_content.present?
        survey_attempt_path(@survey, @attempt_builder.to_model)
      else
        surveys_path
      end
    end

    def rapidfire_current_scoped
      send 'current_'+scoped.to_s
    end
  end
end

app/controllers/rapidfire/questions_controller.rb
module Rapidfire
  class QuestionsController < Rapidfire::ApplicationController
    before_action :authenticate_administrator!
    before_action :find_survey!
    before_action :find_question!, :only => [:edit, :update, :destroy]

    def index
      @questions = @survey.questions
    end

    def new
      @question_form = QuestionForm.new(:survey => @survey)
    end

    def create
      form_params = question_params.merge(:survey => @survey)

      save_and_redirect(form_params, :new)
    end

    def edit
      @question_form = QuestionForm.new(:question => @question)
    end

    def update
      form_params = question_params.merge(:question => @question)
      save_and_redirect(form_params, :edit)
    end

    def destroy
      @question.destroy
      respond_to do |format|
        format.html { redirect_to index_location }
        format.js
      end
    end

    private

    def save_and_redirect(params, on_error_key)
      @question_form = QuestionForm.new(params)
      @question_form.save

      if @question_form.errors.empty?
        respond_to do |format|
          format.html { redirect_to index_location }
          format.js
        end
      else
        respond_to do |format|
          format.html { render on_error_key.to_sym }
          format.js
        end
      end
    end

    def find_survey!
      @survey = Survey.find(params[:survey_id])
    end

    def find_question!
      @question = @survey.questions.find(params[:id])
    end

    def index_location
      rapidfire.survey_questions_url(@survey)
    end

    def question_params
      params.require(:question).permit!
    end
  end
end

app/controllers/rapidfire/surveys_controller.rb
module Rapidfire
  class SurveysController < Rapidfire::ApplicationController
    before_action :authenticate_administrator!, except: :index

    def index
      @surveys = if defined?(Kaminari)
        Survey.page(params[:page])
      else
        Survey.all
      end
    end

    def new
      @survey = Survey.new
    end

    def create
      @survey = Survey.new(survey_params)
      if @survey.save
        respond_to do |format|
          format.html { redirect_to surveys_path }
          format.js
        end
      else
        respond_to do |format|
          format.html { render :new }
          format.js
        end
      end
    end

    def edit
      @survey = Survey.find(params[:id])
    end

    def update
      @survey = Survey.find(params[:id])
      if @survey.update(survey_params)
        respond_to do |format|
          format.html { redirect_to surveys_path }
          format.js
        end
      else
        respond_to do |format|
          format.html { render :edit }
          format.js
        end
      end
    end

    def destroy
      @survey = Survey.find(params[:id])
      @survey.destroy

      respond_to do |format|
        format.html { redirect_to surveys_path }
        format.js
      end
    end

    def results
      @survey = Survey.find(params[:id])
      @survey_results =
        SurveyResults.new(survey: @survey).extract

      respond_to do |format|
        format.json { render json: @survey_results, root: false }
        format.html
        format.js
      end
    end

    private

    def survey_params
      params.require(:survey).permit(:name, :introduction, :after_survey_content)
    end
  end
end

app/helpers/rapidfire/application_helper.rb
module Rapidfire
  module ApplicationHelper
    def render_answer_form_helper(answer, form)
      partial = answer.question.type.to_s.split("::").last.downcase
      render partial: "answer_wrapper", locals: { f: form, answer: answer, partial: partial }
    end

    def checkbox_checked?(answer, option)
      answers_delimiter = Rapidfire.answers_delimiter
      answers = answer.answer_text.to_s.split(answers_delimiter)
      answers.include?(option)
    end

  end
end

app/views/rapidfire/questions/_form.html.erb
<h3>Question</h3>

<%= form_for form, as: :question, url: url, method: method do |f| %>
  <%- unless form.errors.empty? %>
    <ul>
      <%- form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :type %>
    <%= f.select :type, ::Rapidfire::QuestionForm::QUESTION_TYPES, {}, id: "question_type" %>
  </div>

  <div class="form-group">
    <%= f.label :question_text %>
    <%= f.text_field :question_text %>
  </div>

  <div class="form-group">
    <%= f.label :position %>
    <%= f.number_field :position %>
  </div>

  <div class="form-group">
    <%= f.label :placeholder %>
    <%= f.text_field :placeholder %>
  </div>

  <div class="form-group">
    <%= f.label :default_text %>
    <%= f.text_field :default_text %>
  </div>

  <div class="form-group">
    <%= f.label :answer_options %>
    <%= f.text_area :answer_options, rows: 5 %>
  </div>

    <h4>Other options</h4>
    <hr/>

  <div class="form-group">
    <%= f.label :answer_presence %>
    <%= f.check_box :answer_presence %>
  </div>

  <div class="form-group">
    <%= f.label :answer_minimum_length %>
    <%= f.text_field :answer_minimum_length %>
  </div>

  <div class="form-group">
    <%= f.label :answer_maximum_length %>
    <%= f.text_field :answer_maximum_length %>
  </div>

  <div class="form-group">
    <%= f.label :answer_greater_than_or_equal_to %>
    <%= f.text_field :answer_greater_than_or_equal_to %>
  </div>

  <div class="form-group">
    <%= f.label :answer_less_than_or_equal_to %>
    <%= f.text_field :answer_less_than_or_equal_to %>
  </div>

  <%= f.submit submit_text %>
<% end %>

app/views/rapidfire/questions/_question.html.erb
<tr id="question_<%= question.id %>">
  <td><%= question.question_text %></td>
  <td>
    <ul class="horizontal-list">
      <li><%= link_to "Edit", [:edit, question.survey, question] %></li>
      <li><%= link_to "Delete", [question.survey, question], method: :delete %></li>
    </ul>
  </td>
</tr>

app/views/rapidfire/questions/edit.html.erb
<%= render partial: 'form', locals: { form: @question_form, url: survey_question_path(@survey, @question), method: :put, submit_text: 'Update Question' } %>

app/views/rapidfire/questions/index.html.erb
<h2>
  <%= t('rapidfire.questions.header') -%>
</h2>
<h3>
  <%= link_to t('rapidfire.questions.new'), new_survey_question_path(@survey) %>
</h3>
<h4>
  <%= link_to t('rapidfire.questions.back'), surveys_path(@survey) %>
</h4>
<hr/>

<table>
  <colgroup>
    <col>
    <col width="250">
  </colgroup>
  <thead>
    <tr>
      <th><%= t('rapidfire.questions.question') -%></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "question", collection: @questions %>
  </tbody>
</table>

app/views/rapidfire/questions/new.html.erb
<%= render partial: 'form', locals: { form: @question_form, url: survey_questions_path(@survey), method: :post, submit_text: 'Create Question' } %>